### ISSUE TITLE
Error missing module after fresh install

### ISSUE THREAD

**Issue by marceldehoog** [xybu/onedrived-dev#10]
After fresh install when trying to run onedrived-pref (with any options) I get the following error:

Traceback (most recent call last):
  File "/home/marcel/.local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/marcel/.local/lib/python3.5/site-packages/onedrived/od_pref.py", line 11, in <module>
    from . import mkdir, od_auth
  File "/home/marcel/.local/lib/python3.5/site-packages/onedrived/od_auth.py", line 15, in <module>
    from .od_models import account_profile
ImportError: No module named 'onedrived.od_models'

Running Ubuntu 16.04.

**Comment by ireuz** [comment]
same problem here

**Comment by xybu** [comment]
I think the commit dce21b439c2588a35de6242d03a5a2796d8716d3 solved the issue, which seemed to be indicated by #18.
