### ISSUE TITLE
ERROR: Child exited immediately with exit code 127

### ISSUE THREAD

**Issue by newmyl** [xybu/onedrived-dev#102]
I use the KDE-desktop. When I try to start the deamon, it says that "ERROR: Child exited immediately with exit code 127". And When I used the debug model, the error is likely in kwallet.
When use other desktops, there is no error. Why?

onedrived start --debug
Starting onedrived ... OK                                                                                                                                                                       
[2018-07-03 23:42:12,362] ERROR: MainThread: Introspect error on :1.144:/modules/kwalletd5: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying                                                                                                                                                                 
[2018-07-03 23:42:12,362] DEBUG: MainThread: Executing introspect queue due to error                                                                                                            
Traceback (most recent call last):                                                                                                                                                              
  File "/home/myl/.local/lib/python3.6/site-packages/keyring/backends/kwallet.py", line 88, in connected                                                                                        
    self.iface.networkWallet(), wId, self.appid)                                                                                                                                                
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__                                                                                                                   
    return self._proxy_method(*args, **keywords)                                                                                                                                                
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__                                                                                                                  
    **keywords)                                                                                                                                                                                 
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking                                                                                                          
    message, timeout)                                                                                                                                                                           
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.144 was not provided by any .service files

**Comment by derrix060** [comment]
exit code 127 is raised when a command was not found. 

Can you post what version of keyring are you using? Check it running `pip3 freeze | grep keyring`

Also, see #105.

**Comment by algorizan** [comment]
I'm having this same problem. 
I looked my keyring version with the command above and it's 18.0.1
