### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by brauliobo** [xybu/onedrived-dev#105]
```
~ ❯❯❯ onedrived start --debug
Traceback (most recent call last):
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/backends/kwallet.py", line 37, in priority
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
AttributeError: module 'dbus' has no attribute 'SessionBus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/braulio/.local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/braulio/.local/lib/python3.6/site-packages/onedrived/od_main.py", line 20, in <module>
    from .od_auth import get_authenticator_and_drives
  File "/home/braulio/.local/lib/python3.6/site-packages/onedrived/od_auth.py", line 15, in <module>
    from . import od_api_session
  File "/home/braulio/.local/lib/python3.6/site-packages/onedrived/od_api_session.py", line 6, in <module>
    import keyring
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/core.py", line 154, in <module>
    init_backend()
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/core.py", line 67, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/backend.py", line 179, in get_all_keyring
    exceptions=TypeError))
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/backend.py", line 171, in is_class_viable
    keyring_cls.priority
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/braulio/.local/lib/python3.6/site-packages/keyring/backends/kwallet.py", line 38, in priority
    except dbus.DBusException as exc:
AttributeError: module 'dbus' has no attribute 'DBusException'
```

**Comment by derrix060** [comment]
Duplicates #93

**Comment by brauliobo** [comment]
fixed by installing `python-dbus` package from archlinux
