### ISSUE TITLE
Not retrieving files from all folders, now ConnectionRefusedError

### ISSUE THREAD

**Issue by evanperryg** [xybu/onedrived-dev#106]
onedrived has not been downloading files to all folders- this seems to only second level and deeper directories (meaning it pulls all files at the Onedrive root, and everything in the first level of folders, but does not populate the subdirectories from there). It now also throws this error when trying to send it any command:

```
Traceback (most recent call last):
  File "/home/evan/.local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/evan/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_main.py", line 20, in <module>
    from .od_auth import get_authenticator_and_drives
  File "/home/evan/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_auth.py", line 15, in <module>
    from . import od_api_session
  File "/home/evan/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_api_session.py", line 6, in <module>
    import keyring
  File "/usr/local/lib/python3.5/dist-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.5/dist-packages/keyring/core.py", line 154, in <module>
    init_backend()
  File "/usr/local/lib/python3.5/dist-packages/keyring/core.py", line 67, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/local/lib/python3.5/dist-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 179, in get_all_keyring
    exceptions=TypeError))
  File "/usr/local/lib/python3.5/dist-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 171, in is_class_viable
    keyring_cls.priority
  File "/usr/local/lib/python3.5/dist-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/local/lib/python3.5/dist-packages/keyring/backends/SecretService.py", line 37, in priority
    bus = secretstorage.dbus_init()
  File "/usr/local/lib/python3.5/dist-packages/secretstorage/__init__.py", line 41, in dbus_init
    return connect_and_authenticate()
  File "/usr/local/lib/python3.5/dist-packages/jeepney/integrate/blocking.py", line 72, in connect_and_authenticate
    sock.connect(bus_addr)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by evanperryg** [comment]
Forgot to note- the error is only thrown when not using sudo, while I was previously able to run onedrived without sudo. Not sure if that's something that changed on my side, or a side effect of whatever's going on with the downloads.

**Comment by valerius21** [comment]
Having the same Error on Ubuntu 18.04 with the distro default python3, since the upgraded pip3 does not work with it.

**Comment by derrix060** [comment]
@evanperryg can you check if ngrok is in your path?
