### ISSUE TITLE
Couldn't install through pip3 on RPi3

### ISSUE THREAD

**Issue by 45gfg9** [xybu/onedrived-dev#121]
When `python3 ./setup.py test`:
```
running test
Searching for arrow
Best match: arrow 0.13.1
Processing arrow-0.13.1-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/arrow-0.13.1-py3.5.egg
Searching for bidict
Best match: bidict 0.18.0
Processing bidict-0.18.0-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/bidict-0.18.0-py3.5.egg
Searching for inotify_simple
Best match: inotify-simple 1.1.8
Processing inotify_simple-1.1.8-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/inotify_simple-1.1.8-py3.5.egg
Searching for daemonocle>=1.0.1
Best match: daemonocle 1.0.1
Processing daemonocle-1.0.1-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/daemonocle-1.0.1-py3.5.egg
Searching for onedrivesdk
Best match: onedrivesdk 1.1.8
Processing onedrivesdk-1.1.8-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/onedrivesdk-1.1.8-py3.5.egg
Searching for python-dateutil
Best match: python-dateutil 2.8.0
Processing python_dateutil-2.8.0-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/python_dateutil-2.8.0-py3.5.egg
Searching for requests-mock
Best match: requests-mock 1.5.2
Processing requests_mock-1.5.2-py3.5.egg

Using /home/pi/onedrived-dev/.eggs/requests_mock-1.5.2-py3.5.egg
running egg_info
writing entry points to onedrived.egg-info/entry_points.txt
writing onedrived.egg-info/PKG-INFO
writing requirements to onedrived.egg-info/requires.txt
writing dependency_links to onedrived.egg-info/dependency_links.txt
writing top-level names to onedrived.egg-info/top_level.txt
reading manifest file 'onedrived.egg-info/SOURCES.txt'
writing manifest file 'onedrived.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/root/.config/onedrived/onedrived_config_v2.json'. Use default.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/root/.config/onedrived/onedrived_config_v2.json'. Use default.
test_execution (tests.test_webhook_worker.TestWebhookWorker) ... ERROR:root:Unknown subscription ID "233".
ok
test_init_and_shutdown_task_workers (tests.test_main_cli.TestMainCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpfns5_69r/onedrived/onedrived_config_v2.json'. Use default.
ok
test_add_drive (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp6yk4d4qp/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

All available Drives of authorized accounts:

#    Account Email    Drive ID    Type    Quota    Status
---  ---------------  ----------  ------  -------  --------

Did not find existing account with email address "xybu92@live.com".
/usr/lib/python3.5/tempfile.py:937: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpadq4hkcp'>
  _warnings.warn(warn_message, ResourceWarning)
ok
test_authenticate_account_with_code (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp9st9kfcq/onedrived/onedrived_config_v2.json'. Use default.
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Successfully authorized onedrived.
Please enter password for encrypted keyring:
/usr/lib/python3/dist-packages/keyrings/alt/file_base.py:74: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
  password_encrypted = base64.decodestring(password_base64)
/usr/lib/python3/dist-packages/keyrings/alt/file.py:164: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
  data[key] = base64.decodestring(data[key].encode())
/usr/lib/python3/dist-packages/keyrings/alt/file.py:157: DeprecationWarning: encodestring() is a deprecated alias, use encodebytes()
  data[key] = base64.encodestring(data[key]).decode()
/usr/lib/python3/dist-packages/keyrings/alt/file_base.py:90: DeprecationWarning: encodestring() is a deprecated alias, use encodebytes()
  password_base64 = base64.encodestring(password_encrypted).decode()
Successfully added account for Xiangyu Bu (foo@bar.com)!

All OneDrive accounts associated with user "root":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_authenticate_account_with_url (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp9vcutub0/onedrived/onedrived_config_v2.json'. Use default.
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Paste this URL into your browser to sign in and authorize onedrived:

https://login.live.com/oauth20_authorize.srf?scope=wl.signin+wl.emails+wl.offline_access+onedrive.readwrite&client_id=000000004010C916&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf&response_type=code

The authentication web page will finish with a blank page whose URL starts with "https://login.live.com/oauth20_desktop.srf". Paste this URL after the prompt.
Successfully authorized onedrived.
Successfully added account for Xiangyu Bu (foo@bar.com)!

All OneDrive accounts associated with user "root":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_config_print (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpvtblpqib/onedrived/onedrived_config_v2.json'. Use default.
# Path to log file. Empty string means writing to stdout.
logfile_path =

# Total number of worker threads.
num_workers = 2

# Interval, in seconds, between two actions of scanning the entire repository.
scan_interval_sec = 21600

# Amount of time, in seconds, to sleep before main starts working.
start_delay_sec = 0

# Wait for this period of time before acting (usually a merge action) after a webhook notification is received. During this period duplicate notifications can be merged.
webhook_action_delay_sec = 120

# Hostname in webhook URL. Used in "direct" webhook and must resolve to local host. Leave blank to use public IP of the machine.
webhook_host =

# Port number for webhook. Default: 0 (let OS allocate a free port).
webhook_port = 0

# Renew webhook after this amount of time, in seconds. Ideal value should be slightly larger than the lifespan of onedrived process.
webhook_renew_interval_sec = 7200

# Type of webhook. Use "direct" only if your machine can be reached from public network.
webhook_type = ngrok

ok
test_config_set_invalid_str (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp0nfqa7yy/onedrived/onedrived_config_v2.json'. Use default.
Invalid value "whatever" for "webhook_type": must be a choice from direct, ngrok.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp0nfqa7yy/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "logfile_path": path "/" is not a file.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp0nfqa7yy/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "webhook_port": no more than 65535; got 70000.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp0nfqa7yy/onedrived/onedrived_config_v2.json'. Use default.
Invalid value for "num_workers": no less than 1; got 0.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp0nfqa7yy/onedrived/onedrived_config_v2.json'. Use default.
ok
test_config_set_key_typo (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp5bqekckr/onedrived/onedrived_config_v2.json'. Use default.
Usage: setup.py [OPTIONS] KEY VALUE

Error: Invalid value for "key": invalid choice: webhook_typo. (choose from logfile_path, num_workers, scan_interval_sec, start_delay_sec, webhook_action_delay_sec, webhook_host, webhook_port, webhook_renew_interval_sec, webhook_type)
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmp5bqekckr/onedrived/onedrived_config_v2.json'. Use default.
ok
test_config_set_valid (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmppjfu913f/onedrived/onedrived_config_v2.json'. Use default.
config.webhook_type = direct
config.webhook_port = 0
config.logfile_path = /tmp/tmppjfu913f/test.log
ok
test_del_drive (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpx906y092/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

All available Drives of authorized accounts:

  #  Account Email    Drive ID     Type      Quota                            Status
---  ---------------  -----------  --------  -------------------------------  --------
  0  foo@bar.com      xb_drive_id  personal  5.3 GB Used / 33.0 GB Total      active
  1  foo@bar.com      xybu_id      personal  502.0 KB Used / 1000.0 KB Total  active

Did not find existing account with email address "xybu92@live.com".
/usr/lib/python3.5/tempfile.py:937: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpu367daqw'>
  _warnings.warn(warn_message, ResourceWarning)
Drives that have been set up:
 No Drive has been setup with onedrived.

ok
test_list_account (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpway5cmdo/onedrived/onedrived_config_v2.json'. Use default.
All OneDrive accounts associated with user "root":

  #  Account ID    Owner Name    Email Address
---  ------------  ------------  ---------------
  0  713d61        Xiangyu Bu    foo@bar.com
ok
test_list_drives (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmptsrx5inq/onedrived/onedrived_config_v2.json'. Use default.
Reading drives information from OneDrive server...

All available Drives of authorized accounts:

  #  Account Email    Drive ID     Type      Quota                            Status
---  ---------------  -----------  --------  -------------------------------  --------
  0  foo@bar.com      xb_drive_id  personal  5.3 GB Used / 33.0 GB Total      active
  1  foo@bar.com      xybu_id      personal  502.0 KB Used / 1000.0 KB Total  active

Drives that have been set up:
 No Drive has been setup with onedrived.

ok
test_quota_short_str (tests.test_pref_cli.TestPrefCLI) ... WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/tmp/tmpojdjpztw/onedrived/onedrived_config_v2.json'. Use default.
ok
test_config_schema (tests.test_dict_guard.TestConfigSchema) ... ok
test_set_arbitrary_key (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int_above_max (tests.test_dict_guard.TestDictGuard) ... ok
test_set_int_below_min (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_create_file_if_missing (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_empty (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_out_of_choice (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_to_int (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_with_non_file_path (tests.test_dict_guard.TestDictGuard) ... ok
test_set_str_with_permission_denied (tests.test_dict_guard.TestDictGuard) ... FAIL
test_str_not_starts_with (tests.test_dict_guard.TestDictGuard) ... ok
test_str_with_permission_allowed (tests.test_dict_guard.TestDictGuard) ... ok
test_recognize_event_patterns (tests.test_watcher.TestLocalRepositoryWatcher) ... ok
test_lifecycle (tests.test_threads.TestTaskWorkerThread) ... ok
test_properties (tests.test_models.TestAccountProfile) ... ok
test_to_string (tests.test_models.TestAccountProfile) ... ok
test_use (tests.test_models.TestBidict) ... ok
test_properties (tests.test_models.TestDriveConfig) ... ok
test_add_rules (tests.test_models.TestPathFilter) ... ok
test_auto_correction (tests.test_models.TestPathFilter) ... ok
test_hardcoded_cases (tests.test_models.TestPathFilter) ... ok
test_ignore_general (tests.test_models.TestPathFilter) ... ok
test_ignore_in_root (tests.test_models.TestPathFilter) ... ok
test_ignore_path (tests.test_models.TestPathFilter) ... ok
test_negations (tests.test_models.TestPathFilter) ... ok
test_special_patterns (tests.test_models.TestPathFilter) ... ok
test_pretty_print_bytes (tests.test_models.TestPrettyApi) ... ok
test_properties (tests.test_models.TestWebhookNotification) ... ok
test_properties_missing_context (tests.test_models.TestWebhookNotification) ... ok
test_properties_missing_tenant_id (tests.test_models.TestWebhookNotification) ... ok
test_add_get_items (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_delete_file (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_delete_folder (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_get_immediate_children (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_get_immediate_children_of_root (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_move_item_down (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_move_item_up (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_properties (tests.test_repo.TestOneDriveLocalRepository) ... ok
test_expires_in (tests.test_api_session.OneDriveAPISession) ... ok
test_save_and_load (tests.test_api_session.OneDriveAPISession) ... ok
test_get_login_username (tests.test_context.TestUserContext) ... ok
test_get_os_stat (tests.test_tasks.TestMergeDirTask) ... ok
test_list_local_names (tests.test_tasks.TestMergeDirTask) ... ok
test_remote_dir_matches_record (tests.test_tasks.TestMergeDirTask) ... ok
test_rename_with_suffix (tests.test_tasks.TestMergeDirTask) ... ok
test_rename_with_suffix_and_count (tests.test_tasks.TestMergeDirTask) ... ok
test_handle (tests.test_tasks.TestStartRepositoryTask) ... ok
test_task_base (tests.test_tasks.TestTaskBase) ... ok
test_handle_create (tests.test_tasks.TestUpdateSubscriptionTask) ... ok
test_handle_update (tests.test_tasks.TestUpdateSubscriptionTask) ... ok
test_get_auth_url (tests.test_auth.TestOneDriveAuthenticator) ... ok
test_get_proxies (tests.test_auth.TestOneDriveAuthenticator) ... ok
test_get_item_created_datetime (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_modifiable (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_unmodifiable (tests.test_api_helper.TestApiHelper) ... ok
test_item_request_call_on_connection_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered connection error: . Retry in 60 sec.
ok
test_item_request_call_on_unauthorized_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered API Error: unauthenticated - dummy.
ok
test_datetime_to_str (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_explicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_implicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_non_utc (tests.test_dateutils.TestDateUtils) ... ok
test_diff_timestamps (tests.test_dateutils.TestDateUtils) ... ok
test_str_to_datetime (tests.test_dateutils.TestDateUtils) ... ok
test_add_pop (tests.test_task_pool.TestTaskPool) ... ok
test_has_pending_task (tests.test_task_pool.TestTaskPool) ... ok
test_occupy_failure (tests.test_task_pool.TestTaskPool) ... ok
test_occupy_release_path (tests.test_task_pool.TestTaskPool) ... ok
test_remove_children_tasks (tests.test_task_pool.TestTaskPool) ... ok
test_hash (tests.test_hashutils.TestHashUtils) ... ok
test_hash_match (tests.test_hashutils.TestHashUtils) ... ok
test_get_filename_with_incremented_count (tests.test_stringutils.TestStringUtils) ... ok

======================================================================
FAIL: test_set_str_with_permission_denied (tests.test_dict_guard.TestDictGuard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/onedrived-dev/tests/test_dict_guard.py", line 120, in test_set_str_with_permission_denied
    self.assertTrue(ex_raised)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 86 tests in 212.127s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=86 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=86 errors=0 failures=1>
```
When install: 
```
Obtaining file:///home/pi/onedrived-dev
Collecting arrow (from onedrived==2.0.0)
  Downloading https://files.pythonhosted.org/packages/f4/7f/0360628ba40bb93c10cd89cd289b6a8e9ea87b2db884b8edf32c80ee1c73/arrow-0.13.1-py2.py3-none-any.whl
Collecting bidict (from onedrived==2.0.0)
  Downloading https://files.pythonhosted.org/packages/10/db/0f688f4ed1ff18a7bdfc868dd879e71fcd3cb3b01ca22af5f49968102258/bidict-0.18.0-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 55kB/s
Requirement already satisfied: click>=6.6 in /usr/lib/python3/dist-packages (from onedrived==2.0.0)
Requirement already satisfied: colorama>=0.3.7 in /usr/lib/python3/dist-packages (from onedrived==2.0.0)
Collecting daemonocle>=1.0.1 (from onedrived==2.0.0)
  Downloading https://www.piwheels.org/simple/daemonocle/daemonocle-1.0.1-py3-none-any.whl
Collecting inotify_simple (from onedrived==2.0.0)
  Downloading https://www.piwheels.org/simple/inotify-simple/inotify_simple-1.1.8-py3-none-any.whl
Requirement already satisfied: keyring>=10.1 in /usr/lib/python3/dist-packages (from onedrived==2.0.0)
Collecting onedrivesdk (from onedrived==2.0.0)
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by 45gfg9** [comment]
This is weird...
Problem solved by doing `pip3 install onedrivesdk` first.
Btw thanks for your project!
