### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mac-mvak** [xybu/onedrived-dev#135]
Hello, I can't install this program as I have a error

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1xlvgmdw/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1xlvgmdw/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1olegzwp
         cwd: /tmp/pip-install-1xlvgmdw/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1xlvgmdw/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-1xlvgmdw/onedrivesdk/setup.py/../NOTICE.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by heri3x** [comment]
Same here.

Ubuntu 20.04, Python 3.8.2
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by abraunegg** [comment]
@Mac-Nikak , @heri3x 

Given the code was last updated on Jan 14, 2019 - I would say this client for OneDrive is stale.

The OneDrive client that I actively maintain can be found here:
* https://abraunegg.github.io/
* https://github.com/abraunegg/onedrive
