### ISSUE TITLE
can't configure

### ISSUE THREAD

**Issue by zzavatar09** [xybu/onedrived-dev#136]
when i use onedrived or  onedrived-pre,
it response as following:
Traceback (most recent call last):
  File "/home/administrator/.local/bin/onedrived", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/.local/bin/onedrived", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/.local/bin/onedrived", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3256, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'onedrivesdk' distribution was not found and is required by onedrived

**Comment by abraunegg** [comment]
@zzavatar09 

Given the code was last updated on Jan 14, 2019 - I would say this client for OneDrive is stale and not maintained.

The OneDrive client that I actively maintain can be found here:
* https://abraunegg.github.io/
* https://github.com/abraunegg/onedrive
