### ISSUE TITLE
error when downloading onedrivesdk-2.0tat.gz

### ISSUE THREAD

**Issue by jdavid54** [xybu/onedrived-dev#137]
pip3 install --user git+https://github.com/xybu/onedrived-dev.git
Collecting git+https://github.com/xybu/onedrived-dev.git
  Cloning https://github.com/xybu/onedrived-dev.git to /tmp/pip-req-build-s_uc21ee
Collecting arrow
  Downloading arrow-0.16.0-py2.py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 1.3 MB/s 
Collecting bidict
  Downloading bidict-0.21.0-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: click>=6.6 in /usr/lib/python3/dist-packages (from onedrived==2.0.0) (7.0)
Requirement already satisfied: colorama>=0.3.7 in /usr/lib/python3/dist-packages (from onedrived==2.0.0) (0.4.3)
Collecting daemonocle>=1.0.1
  Downloading daemonocle-1.0.2.tar.gz (25 kB)
Collecting inotify_simple
  Downloading inotify_simple-1.3.5.tar.gz (9.7 kB)
Requirement already satisfied: keyring>=10.1 in /usr/lib/python3/dist-packages (from onedrived==2.0.0) (18.0.1)

====================================================================OK until here

Collecting onedrivesdk
  Downloading onedrivesdk-2.0.tar.gz (1.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fnt031go/onedrivesdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fnt031go/onedrivesdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ubplvuvz
         cwd: /tmp/pip-install-fnt031go/onedrivesdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fnt031go/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-fnt031go/onedrivesdk/setup.py/../NOTICE.rst'

**Comment by abraunegg** [comment]
@jdavid54 

Given the code was last updated on Jan 14, 2019 - I would say this client for OneDrive is stale and not maintained.

The OneDrive client that I actively maintain can be found here:
* https://abraunegg.github.io/
* https://github.com/abraunegg/onedrive
