### ISSUE TITLE
error with config command : onedrived-pref account add

### ISSUE THREAD

**Issue by jdavid54** [xybu/onedrived-dev#138]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 2, in <module>
    from bidict import loosebidict
ImportError: cannot import name 'loosebidict' from 'bidict' (/usr/local/lib/python3.8/dist-packages/bidict-0.21.0-py3.8.egg/bidict/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_auth.py", line 16, in <module>
    from .od_models import account_profile
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/__init__.py", line 1, in <module>
    from . import account_profile, bidict, drive_config, path_filter, pretty_api, webhook_notification
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 5, in <module>
    class loosebidict(bidict.bidict):
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 6, in loosebidict
    on_dup_val = bidict.OVERWRITE
AttributeError: module 'bidict' has no attribute 'OVERWRITE'

**Comment by abraunegg** [comment]
@jdavid54 

Given the code was last updated on Jan 14, 2019 - I would say this client for OneDrive is stale and not maintained.

The OneDrive client that I actively maintain can be found here:
* https://abraunegg.github.io/
* https://github.com/abraunegg/onedrive
