### ISSUE TITLE
error with bidict 0.21.0

### ISSUE THREAD

**Issue by jdavid54** [xybu/onedrived-dev#139]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 2, in <module>
    from bidict import loosebidict
ImportError: cannot import name 'loosebidict' from 'bidict' (/usr/local/lib/python3.8/dist-packages/bidict-0.21.0-py3.8.egg/bidict/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_auth.py", line 16, in <module>
    from .od_models import account_profile
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/__init__.py", line 1, in <module>
    from . import account_profile, bidict, drive_config, path_filter, pretty_api, webhook_notification
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 5, in <module>
    class loosebidict(bidict.bidict):
  File "/usr/local/lib/python3.8/dist-packages/onedrived-2.0.0-py3.8.egg/onedrived/od_models/bidict.py", line 6, in loosebidict
    on_dup_val = bidict.OVERWRITE
AttributeError: module 'bidict' has no attribute 'OVERWRITE'

**Comment by jdavid54** [comment]
solution :+1: 
sudo pip3 install --upgrade bidict==0.13.1
Collecting bidict==0.13.1
  Downloading bidict-0.13.1.tar.gz (14 kB)
Building wheels for collected packages: bidict
  Building wheel for bidict (setup.py) ... done
  Created wheel for bidict: filename=bidict-0.13.1-py3-none-any.whl size=16972 sha256=8c5b9a038e807aa5b63574eaca76f7107d57e8540b3b3359b126e7d7d50f6b0c
  Stored in directory: /root/.cache/pip/wheels/36/18/63/1c6bc8ad2688229ad4dd672444dd5cbe9bb748ee95fd7ef2dc
Successfully built bidict
Installing collected packages: bidict
  Attempting uninstall: bidict
    Found existing installation: bidict 0.21.0
    Uninstalling bidict-0.21.0:
      Successfully uninstalled bidict-0.21.0
Successfully installed bidict-0.13.1

**Comment by abraunegg** [comment]
@jdavid54 

Given the code was last updated on Jan 14, 2019 - I would say this client for OneDrive is stale and not maintained.

The OneDrive client that I actively maintain can be found here:
* https://abraunegg.github.io/
* https://github.com/abraunegg/onedrive
