### ISSUE TITLE
 onedrived start --debug error

### ISSUE THREAD

**Issue by zsvoboda** [xybu/onedrived-dev#19]
Succesfully configured the drive (OAuth, local dir etc.) then onedrived start --debug

Starting onedrived ... OK
[2017-02-02 00:13:03,322] DEBUG: MainThread: Starting new HTTPS connection (1): api.onedrive.com
[2017-02-02 00:13:03,659] DEBUG: MainThread: https://api.onedrive.com:443 "GET /v1.0/drives HTTP/1.1" 200 376
[2017-02-02 00:13:03,706] DEBUG: MainThread: Refreshing repository session.
[2017-02-02 00:13:03,707] DEBUG: MainThread: Starting new HTTPS connection (1): login.live.com
[2017-02-02 00:13:05,088] DEBUG: MainThread: https://login.live.com:443 "POST /oauth20_token.srf HTTP/1.1" 200 1647
[2017-02-02 00:13:05,211] INFO: MainThread: Session for account 4bb28fecf8dc48f2 will expire in 3599 seconds.
[2017-02-02 00:13:05,211] DEBUG: MainThread: Will refresh session in 3479 seconds.
[2017-02-02 00:13:05,213] INFO: MainThread: Sweeping onedrived temporary files from local repositories.
[2017-02-02 00:13:05,216] DEBUG: Worker-0: Started.
[2017-02-02 00:13:05,217] DEBUG: Worker-1: Started.
[2017-02-02 00:13:05,225] CRITICAL: MainThread: ngrok process (pid 13842) terminated early with return code 1. Command: "ngrok http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml".
Traceback (most recent call last):
  File "/home/zdenek/.local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/home/zdenek/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/cli.py", line 57, in subcommand
    daemon.do_action(name)
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/core.py", line 608, in do_action
    func()
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/core.py", line 477, in start
    self._run()
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/core.py", line 399, in _run
    self.worker()
  File "/home/zdenek/.local/lib/python3.5/site-packages/onedrived/od_main.py", line 184, in main
    webhook_server = od_webhook.get_webhook_server(context)
  File "/home/zdenek/.local/lib/python3.5/site-packages/onedrived/od_webhook.py", line 28, in get_webhook_server
    return WebhookListener(wh_config, OneDriveWebhookHandler)
  File "/home/zdenek/.local/lib/python3.5/site-packages/onedrived/od_webhooks/ngrok_server.py", line 39, in __init__
    self._start_ngrok_process(cmd)
  File "/home/zdenek/.local/lib/python3.5/site-packages/onedrived/od_webhooks/ngrok_server.py", line 68, in _start_ngrok_process
    raise RuntimeError('Ngrok process exited early.')
RuntimeError: Ngrok process exited early.
^C
[2017-02-02 00:13:57,105] INFO: MainThread: Shutting down.
[2017-02-02 00:13:57,109] DEBUG: Worker-0: Stopped.
[2017-02-02 00:13:57,109] DEBUG: Worker-1: Stopped.
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/core.py", line 393, in _handle_terminate
    self._shutdown(message, code=128+signal_number)
  File "/home/zdenek/.local/lib/python3.5/site-packages/daemonocle/core.py", line 382, in _shutdown
    sys.exit(code)
SystemExit: 130
[2017-02-02 00:13:57,117] DEBUG: MainThread: Closing database "/home/zdenek/.config/onedrived/items_4bb28fecf8dc48f2.sqlite3".
[2017-02-02 00:13:57,188] DEBUG: MainThread: Close <_UnixSelectorEventLoop running=False closed=False debug=True>
All children are gone. Parent is exiting...

**Comment by xybu** [comment]
The documentation about `ngrok` is still missing in `README.md`. It's a program that tunnels HTTPS requests from OneDrive server to the machine on which `onedrived` runs. In most cases `onedrived` runs on personal machines that aren't public accessible (e.g., behind NAT) so HTTPS requests can't reach onedrived directly. 

FYI: OneDrive client on Windows connects to a Microsoft Server (cluster), which acts as a multiplexer. OneDrive server sends all HTTPS requests to this multiplexer, and it dispatches those requests to proper users through TCP channels it maintains with the clients. I don't have server clusters powerful to do that kind of job for onedrived. So I used free service from `ngrok` to achieve something similar. Here `ngrok` acts like the multiplexer.

Anyway, do you have `ngrok` (https://ngrok.com/download) installed in `PATH`? If so, could you run command `ngrok http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml` and see why it exited early?

**Comment by zsvoboda** [comment]
Thanks for prompt answer! Here is my console output:

```
zdenek@zd ~ $ ngrok http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml
You may only specify one port to tunnel to on the command line, got 4: [http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml]
zdenek@zd ~ $ cat /home/zdenek/.config/onedrived/ngrok_conf.yaml
console_ui: true
```

**Comment by zsvoboda** [comment]
I've figured it out. I've installed older version of the `ngrok` via `apt install`. Once re-installed via download from `https://ngrok.com/download` everything works fine. Thanks!

**Comment by pauliebp** [comment]
Hi! I am having a similar issue but NGROK update did not help. Here is the console output from `ngrok http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml`

`You may only specify one port to tunnel to on the command line, got 4: [http 42951 --config /home/zdenek/.config/onedrived/ngrok_conf.yaml]`

Here is the log file:
[2017-12-20 06:50:46,762] INFO: MainThread: Session for account 75d3cc56d0751b6c will expire in 3599 seconds.
[2017-12-20 06:50:46,763] INFO: MainThread: Sweeping onedrived temporary files from local repositories.
[2017-12-20 06:50:46,791] CRITICAL: MainThread: ngrok process (pid 4287) terminated early with return code 1. Command: "ngrok http 44403 -bind-tls=true --config /home/pauls/.config/onedrived/ngrok_conf.yaml".
[2017-12-20 06:50:46,792] CRITICAL: MainThread: Error initializing webhook: Ngrok process exited early.
[2017-12-20 06:50:46,792] INFO: MainThread: Shutting down. Code: Exiting with message: None.
[2017-12-20 06:50:46,793] INFO: Worker-0: Stopped.
[2017-12-20 06:50:46,793] INFO: Worker-1: Stopped.
[2017-12-20 06:50:46,793] INFO: MainThread: Shut down complete.

Thanks in advance for any assistance.

**Comment by TomFarley** [comment]
I'm having the same problem too.

**Comment by unjello** [comment]
FYI. Solved by downloading latest ngrok and putting it in `PATH` (i.e. `/usr/local/bin`) as described in #53.
