### ISSUE TITLE
Error when stopping daemon using 'python3 -m onedrived.od_main stop'

### ISSUE THREAD

**Issue by vk5ztv** [xybu/onedrived-dev#20]
When testing commit 6020bf4, I started onedrived into daemon mode using 'python3 -m onedrived.od_main' - the daemon started successfully. 

'python3 -m onedrived.od_main status' correctly reported 'od_main.py -- pid: 10526, status: sleeping, uptime: 0m, %cpu: 0.0, %mem: 0.4'. 

When running 'python3 -m onedrived.od_main stop' the following occurred: 
Stopping od_main.py ... FAILED
ERROR: Timed out while waiting for process (PID 10526) to terminate

Check the status again reported that the daemon was not running, so it appears it did stop, but it perhaps did not return its exit status?

**Comment by vk5ztv** [comment]
Confirmed the same behaviour occurs after installing onedrived (with commit 6020bf4 applied) using 'sudo pip3 install .' from the source directory and running it with 'onedrived start'.

**Comment by xybu** [comment]
My best guess is that the program is downloading or uploading something when you `stop` it. Need to double check if `stop` works fine when the program is idle.

**Comment by xybu** [comment]
In daemon mode it's the SIGTERM handler that prevents the program from exiting. Will address it soon.

**Comment by vk5ztv** [comment]
The exit problem happens in debug mode as well. I have confirmed (using debug mode) that the program is idle when the exit command is issued (from another console window). In the debug session I see this (I've included the end of the last download to demonstrate that it has been idle for a minute before I told it to shut down):

[2017-02-05 10:46:24,915] DEBUG: MainThread: Move pair ((Event(wd=18, mask=64, cookie=14905, name='.20140925_015811554_iOS.jpg.odtemp!'), [<flags.MOVED_FROM: 64>]), (Event(wd=18, mask=128, cookie=14905, name='20140925_015811554_iOS.jpg'), [<flags.MOVED_TO: 128>])) is result of renaming temp file. No need to handle.
[2017-02-05 10:46:24,915] WARNING: MainThread: Executing <Handle LocalRepositoryWatcher.process_events() created at /usr/lib64/python3.5/asyncio/selector_events.py:232> took 0.201 seconds
[2017-02-05 10:46:24,924] INFO: Worker-0: Finished downloading item "D3838F8EBE5535A6!2024".
[2017-02-05 10:47:33,611] INFO: MainThread: Shutting down.
[2017-02-05 10:47:33,676] INFO: Webhook: Webhook server stopped.
[2017-02-05 10:47:33,676] DEBUG: Worker-1: Stopped.
[2017-02-05 10:47:33,676] DEBUG: Worker-0: Stopped.

It then hangs until Ctrl-C is issued, then: 

^C
[2017-02-05 10:50:28,270] INFO: MainThread: Shutting down.
[2017-02-05 10:50:28,271] DEBUG: MainThread: Close <_UnixSelectorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "/usr/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived', 'console_scripts', 'onedrived')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/daemonocle/cli.py", line 56, in subcommand
    daemon.do_action(name)
  File "/usr/lib/python3.5/site-packages/daemonocle/daemon.py", line 573, in do_action
    func()
  File "/usr/lib/python3.5/site-packages/daemonocle/daemon.py", line 444, in start
    self._run()
  File "/usr/lib/python3.5/site-packages/daemonocle/daemon.py", line 367, in _run
    self.worker()
  File "/usr/local/src/onedrived-dev/onedrived/od_main.py", line 210, in main
    context.loop.run_forever()
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 295, in run_forever
    self._run_once()
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 1199, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.5/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/usr/lib/python3.5/site-packages/daemonocle/daemon.py", line 361, in _handle_terminate
    self._shutdown(message, code=128+signal_number)
  File "/usr/lib/python3.5/site-packages/daemonocle/daemon.py", line 344, in _shutdown
    self.shutdown_callback(message, code)
  File "/usr/local/src/onedrived-dev/onedrived/od_main.py", line 82, in shutdown_callback
    context.watcher.close()
  File "/usr/local/src/onedrived-dev/onedrived/od_watcher.py", line 49, in close
    self.notifier.close()
  File "/usr/lib/python3.5/site-packages/inotify_simple/inotify_simple.py", line 101, in close
    os.close(self.fd)
OSError: [Errno 9] Bad file descriptor
[2017-02-05 10:50:28,277] DEBUG: Dummy-1: Closing database "/home/bakerr/.config/onedrived/items_d3838f8ebe5535a6.sqlite3".
All children are gone. Parent is exiting...

Not sure if this will be helpful or not.

**Comment by xybu** [comment]
The problem above showed a double close. The diff 98fbb99db9e02e86f3edfe6dddf676143bde677f should fix the problem of exiting from debug mode (needs SIGINT) and daemon mode (needs SIGTERM). Sending SIGTERM to debug mode wouldn't work and I didn't try sending SIGINT to daemon mode.
