### ISSUE TITLE
KeyError: 'lastModifiedDateTime'

### ISSUE THREAD

**Issue by Graf17** [xybu/onedrived-dev#29]
Unfortunately I have another problem now. The daemon runs in debug mode, but after a minute or so I get the following error:

[2017-02-24 18:59:57,004] DEBUG: Worker-1: Starting new HTTPS connection (1): api.onedrive.com
[2017-02-24 18:59:57,935] DEBUG: Worker-1: https://api.onedrive.com:443 "PUT /v1.0/drives/5320c3e9841f3c76/root:/Dokumente/Visual%20Studio%202008/Projects/PPC-GC-Tools/PPC-GC-Tools/images/database:/children/setascenter32x32.jpg/content HTTP/1.1" 201 818
Exception in thread Worker-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_api_helper.py", line 60, in get_item_modified_datetime
    return od_dateutils.str_to_datetime(item.file_system_info._prop_dict['lastModifiedDateTime']), True
AttributeError: 'NoneType' object has no attribute '_prop_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_threads.py", line 29, in run
    task.handle()
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_tasks/upload_file.py", line 63, in handle
    self.update_timestamp_and_record(returned_item, item_stat)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_tasks/update_mtime.py", line 30, in update_timestamp_and_record
    remote_mtime, remote_mtime_w = get_item_modified_datetime(new_item)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_api_helper.py", line 63, in get_item_modified_datetime
    return od_dateutils.str_to_datetime(item._prop_dict['lastModifiedDateTime']), False
KeyError: 'lastModifiedDateTime'

**Comment by xybu** [comment]
For this issue, OneDrive server is supposed to return the item metadata in response body according to its API document, yet it occasionally doesn't. I have no idea why and it's sometimes hard to reproduce.

**Comment by Graf17** [comment]
Xybu, thanks again for your answer. The problem is, that onedrived seems to stop working after that error. Do you think it is possible to handle that exception and keep onedrived working?

Thanks again for your affords.

**Comment by xybu** [comment]
You can add a try-catch on the line `task.handle()` in od_threads.TaskWorkerThread.run (https://github.com/xybu/onedrived-dev/blob/master/onedrived/od_threads.py#L29). I don't add this in code base because I need to have bugs exposed...

**Comment by Graf17** [comment]
That seems to work. Thanks for your help!

**Comment by marmarek** [comment]
This is happening for me for every single file now. Adding try/except hides the issue, but does not solve it. Maybe the API change is documented now?
