### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BlakeTrebelhorn** [xybu/onedrived-dev#36]
I kept getting this error on Ubuntu 16.10:
`Error initializing plugin Gnome = keyrings.alt.Gnome.
Traceback (most recent call last):
  File "/home/blake/.local/lib/python3.5/site-packages/keyring/backend.py", line 167, in _load_plugins
    init_func = ep.load()
  File "/home/blake/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/blake/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin kwallet = keyrings.alt.kwallet.
Traceback (most recent call last):
  File "/home/blake/.local/lib/python3.5/site-packages/keyring/backend.py", line 167, in _load_plugins
    init_func = ep.load()
  File "/home/blake/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/blake/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'`

I was able to fix it by running
`sudo pip3 install --upgrade keyrings.alt`
Apparently I had keyrings.atl v1.1.1, and v2.2 fixed the error. Just wanted to post this in case someone else came across the problem so they could fix it themselves.

**Comment by xybu** [comment]
Thanks. This should be documented in the README.

**Comment by jeronimofagundes** [comment]
I also get this on Debian Stretch with keyrings.alt v. 1.3. 
The command mentioned by @BlakeTrebelhorn also solved my problem!
