### ISSUE TITLE
Installation issue, Ubuntu 16.04?

### ISSUE THREAD

**Issue by gladwig2** [xybu/onedrived-dev#37]
after install, following instructions in README
...
Successfully installed arrow-0.10.0 bidict-0.13.1 click-6.7 colorama-0.3.7 daemonocle-1.0.1 inotify-simple-1.1.1 keyring-10.3.2 onedrived onedrivesdk-1.1.8 psutil-5.2.2 python-dateutil-2.6.0 requests-2.13.0 secretstorage-2.3.1 send2trash-1.3.0 tabulate-0.7.7 zgitignore-0.7.1

xyz@server:~/Downloads/onedrived-dev$ onedrived-pref --help
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.secrets': no such name

During handling of the above exception, another exception occurred:
....

Also, commands will execute on the 2nd try, but will take ~60 seconds and will complain about:
xyz@server:~/Downloads/onedrived-dev$ onedrived-pref --help
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/xyz/.config/onedrived/onedrived_config_v2.json'. Use default.
Usage: onedrived-pref [OPTIONS] COMMAND [ARGS]...

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:

Thanks,

**Comment by derrix060** [comment]
with commands did you use to install this?

**Comment by xybu** [comment]
It seems keyrings' dependencies are not properly installed and it can't access the secret storage service. Might you double check keyrings' documentation?
