### ISSUE TITLE
[Python3.3] Exception after test succeeds.

### ISSUE THREAD

**Issue by xybu** [xybu/onedrived-dev#4]
```
xb@ubuntu:[~/Desktop/onedrived-dev]: python3.3 setup.py test
running test
Searching for requests-mock>=0.6
Best match: requests-mock 1.2.0
Processing requests_mock-1.2.0-py3.3.egg

Using /home/xb/Desktop/onedrived-dev/.eggs/requests_mock-1.2.0-py3.3.egg
running egg_info
writing top-level names to onedrived.egg-info/top_level.txt
writing onedrived.egg-info/PKG-INFO
writing requirements to onedrived.egg-info/requires.txt
writing dependency_links to onedrived.egg-info/dependency_links.txt
writing entry points to onedrived.egg-info/entry_points.txt
reading manifest file 'onedrived.egg-info/SOURCES.txt'
writing manifest file 'onedrived.egg-info/SOURCES.txt'
running build_ext
test_get_login_username (tests.test_context.TestUserContext) ... ok
test_get_item_created_datetime (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_modifiable (tests.test_api_helper.TestApiHelper) ... ok
test_get_item_modified_datetime_unmodifiable (tests.test_api_helper.TestApiHelper) ... ok
test_item_request_call_on_connection_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered connection error: . Retry in 60 sec.
ok
test_item_request_call_on_unauthorized_error (tests.test_api_helper.TestApiHelper) ... ERROR:root:Encountered API Error: unauthenticated - dummy.
ok
test_get_filename_with_incremented_count (tests.test_stringutils.TestStringUtils) ... ok
test_properties (tests.test_models.TestAccountProfile) ... ok
test_to_string (tests.test_models.TestAccountProfile) ... ok
test_properties (tests.test_models.TestDriveConfig) ... ok
test_add_rules (tests.test_models.TestPathFilter) ... ok
test_auto_correction (tests.test_models.TestPathFilter) ... ok
test_hardcoded_cases (tests.test_models.TestPathFilter) ... ok
test_ignore_general (tests.test_models.TestPathFilter) ... ok
test_ignore_in_root (tests.test_models.TestPathFilter) ... ok
test_ignore_path (tests.test_models.TestPathFilter) ... ok
test_negations (tests.test_models.TestPathFilter) ... ok
test_special_patterns (tests.test_models.TestPathFilter) ... ok
test_pretty_print_bytes (tests.test_models.TestPrettyApi) ... ok
test_pretty_quota (tests.test_models.TestPrettyApi) ... ok
test_hash (tests.test_hashutils.TestHashUtils) ... ok
test_hash_match (tests.test_hashutils.TestHashUtils) ... ok
test_task_base (tests.test_tasks.TestTaskBase) ... ok
test_datetime_to_str (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_explicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_implicit_utc (tests.test_dateutils.TestDateUtils) ... ok
test_datetime_to_timestamp_non_utc (tests.test_dateutils.TestDateUtils) ... ok
test_diff_timestamps (tests.test_dateutils.TestDateUtils) ... ok
test_str_to_datetime (tests.test_dateutils.TestDateUtils) ... ok
test_add_pop (tests.test_task_pool.TestTaskPool) ... ok
test_has_pending_task (tests.test_task_pool.TestTaskPool) ... ok
test_remove_children_tasks (tests.test_task_pool.TestTaskPool) ... ok
test_properties (tests.test_repo.TestOneDriveLocalRepository) ... ok

----------------------------------------------------------------------
Ran 33 tests in 0.018s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.3/concurrent/futures/thread.py", line 34, in _python_exit
    items = list(_threads_queues.items())
AttributeError: 'NoneType' object has no attribute 'items'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.3/concurrent/futures/process.py", line 78, in _python_exit
    items = list(_threads_queues.items())
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by xybu** [comment]
Doesn't look like an issue originating from onedrived test suites and don't know what's the culprit. Use pytest instead.
