### ISSUE TITLE
AUR Package misses psutil dependency

### ISSUE THREAD

**Issue by Mons1990** [xybu/onedrived-dev#41]
Hi, I have an issue while configuring the share.

```
[mons@arch-desktop ~]$ onedrived-pref --help
Traceback (most recent call last):
  File "/usr/bin/onedrived-pref", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil' distribution was not found and is required by onedrived
```

This happens every time i call _onedrive-pref_ command.
I'm running Arch Linux with the last version of Python3 and installed onedrived-dev via AUR.

Thank you in advance for taking care of this.

**Comment by xybu** [comment]
`sudo pip3 install psutil`

**Comment by Mons1990** [comment]
Solved. It was a bug on the AUR package not on the program. Installing via PIP it works. Sorry for the question and thank you for the useful software you wrote.

**Comment by Azphreal** [comment]
Turns out the AUR package is missing a lot of dependencies, and some of them have PKGBUILDs that need fixing. Install via PIP until I or someone else gets time to fix everything.
