### ISSUE TITLE
[Python 3.3] Cannot find resource file

### ISSUE THREAD

**Issue by xybu** [xybu/onedrived-dev#5]
No such issue on Python 3.4+.

```
xb@ubuntu:[~/Desktop/onedrived-dev]: python3.3 -m onedrived.od_main start --debug
Starting od_main.py ... OK
[2017-01-17 03:02:59,328] DEBUG: MainThread: Starting new HTTPS connection (1): api.onedrive.com
[2017-01-17 03:02:59,632] DEBUG: MainThread: https://api.onedrive.com:443 "GET /v1.0/drives HTTP/1.1" 200 373
Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./onedrived/od_main.py", line 129, in <module>
  File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.3/dist-packages/daemonocle/cli.py", line 57, in subcommand
    daemon.do_action(name)
  File "/usr/local/lib/python3.3/dist-packages/daemonocle/core.py", line 608, in do_action
    func()
  File "/usr/local/lib/python3.3/dist-packages/daemonocle/core.py", line 477, in start
    self._run()
  File "/usr/local/lib/python3.3/dist-packages/daemonocle/core.py", line 399, in _run
    self.worker()
  File "./onedrived/od_main.py", line 106, in main
  File "./onedrived/od_main.py", line 56, in get_repo_table
  File "./onedrived/od_main.py", line 56, in <listcomp>
  File "./onedrived/od_repo.py", line 56, in __init__
  File "./onedrived/od_repo.py", line 74, in _init_item_store
  File "./onedrived/__init__.py", line 43, in get_resource
  File "/usr/lib/python3.3/pkgutil.py", line 640, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1031, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './onedrived/data/items_db.sql'
All children are gone. Parent is exiting...
```

**Comment by xybu** [comment]
Package `daemonocle` seems to not inherit cwd in Py3.3 in the daemon process. Addressed in 65459c1e4f2482f0c2cfc92e4fd7b708684cd287.
