### ISSUE TITLE
Onedrived-pref drive list returns Error: NoneType

### ISSUE THREAD

**Issue by Cole0209** [xybu/onedrived-dev#76]
pi@RaspberryPI:$ onedrived-pref drive list
Reading drives information from OneDrive server...

Error: 'NoneType' object has no attribute 'encode

**Comment by derrix060** [comment]
Can you run this command with `--debug` flag?

**Comment by erssebaggala** [comment]
@derrix060  I am getting a similar error. Any insightn into how to go about this?
```
$ onedrived start --debug
Starting onedrived ... OK
Traceback (most recent call last):
  File "/home/bodastage/.local/bin/onedrived", line 11, in <module>
    sys.exit(main())
  File "/home/bodastage/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bodastage/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bodastage/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bodastage/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bodastage/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bodastage/.local/lib/python3.5/site-packages/daemonocle/cli.py", line 57, in subcommand
    daemon.do_action(name)
  File "/home/bodastage/.local/lib/python3.5/site-packages/daemonocle/core.py", line 608, in do_action
    func()
  File "/home/bodastage/.local/lib/python3.5/site-packages/daemonocle/core.py", line 477, in start
    self._run()
  File "/home/bodastage/.local/lib/python3.5/site-packages/daemonocle/core.py", line 399, in _run
    self.worker()
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrived/od_main.py", line 195, in main
    all_accounts = get_repo_table(context)
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrived/od_main.py", line 101, in get_repo_table
    authenticator, drives = get_authenticator_and_drives(ctx, account_id)
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrived/od_auth.py", line 23, in get_authenticator_and_drives
    authenticator.load_session(key=od_api_session.get_keyring_key(account_id))
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrived/od_auth.py", line 98, in load_session
    self.client.auth_provider.load_session(**args)
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrivesdk/auth_provider.py", line 323, in load_session
    self._session = self._session_type.load_session(**load_session_kwargs)
  File "/home/bodastage/.local/lib/python3.5/site-packages/onedrived/od_api_session.py", line 41, in load_session
    data = zlib.decompress(base64.b64decode(saved_data.encode('utf-8')))
AttributeError: 'NoneType' object has no attribute 'encode'
[2018-11-21 23:08:24,185] DEBUG: Dummy-1: Close <_UnixSelectorEventLoop running=False closed=False debug=True>
All children are gone. Parent is exiting...
```

**Comment by derrix060** [comment]
@erssebaggala looks like there was a problem with your keyring...

- Did you change the keyring version recently? (via linux update, for example)
- Was it working and suddenly stopped?
- How long have you been using this project?

I remember to see this problem and I'm pretty sure I fixed it on my fork, can you test there to see if still failing? https://github.com/derrix060/onedriveClient

**Comment by naanadr** [comment]
I have the same problem. Do you have any suggestion ?

**Comment by derrix060** [comment]
Hello @FernandaSzAdr, can you answer the same questions that I've post above?
