### ISSUE TITLE
Obsolete use of loosebidict/looseorderedbidict

### ISSUE THREAD

**Issue by havoc88** [xybu/onedrived-dev#77]
bidict-0.14.0 (released on 2017-11-20), removed "loosebidict".
From the changelog (https://media.readthedocs.org/pdf/bidict/master/bidict.pdf) :

> loosebidict and looseorderedbidict have been removed. Simple recipes to implement them yourself are now given in OverwritingBidict Recipe.

And I cannot actually use onedrived:

> $ onedrived
Traceback (most recent call last):
  File "/home/debian/.local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/home/debian/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/debian/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/home/debian/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/home/debian/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/debian/.local/lib/python3.5/site-packages/onedrived/od_main.py", line 22, in <module>
    from .od_watcher import LocalRepositoryWatcher
  File "/home/debian/.local/lib/python3.5/site-packages/onedrived/od_watcher.py", line 6, in <module>
    from bidict import loosebidict
ImportError: cannot import name 'loosebidict'

Are you planning to update your software or should we install an old bidict version?
Thanks

**Comment by Daryolo** [comment]
I'm getting the same error by now. Worked flawless before.

**Comment by dloret** [comment]
Hi, I just installed onedrived on Ubuntu 17.10. All went fine but launching "onedrived start --debug", I got the same error:
`$ onedrived start --debug
Traceback (most recent call last):
  File "/usr/local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/onedrived/od_main.py", line 22, in <module>
    from .od_watcher import LocalRepositoryWatcher
  File "/usr/local/lib/python3.6/dist-packages/onedrived/od_watcher.py", line 6, in <module>
    from bidict import loosebidict
ImportError: cannot import name 'loosebidict'`

**Comment by xybu** [comment]
Replace the 

```
from bidict import loosebidict
```

line in od_watcher.py with something like

```
import bidict

class loosebidict(bidict.bidict):
    on_dup_val = bidict.OVERWRITE
```

might work.

**Comment by survivor303** [comment]
its worked, thanks @xybu :)

**Comment by dloret** [comment]
It woorked perfectly fine.

If it can be useful to seomeone, here is where the file was located on my machine (Ubuntu 17.10):
```
$ sudo find . -name od_watcher.py
./usr/local/lib/python3.6/dist-packages/onedrived/od_watcher.py
```
Many thnks for the quick response @xybu !

**Comment by veritas06** [comment]
I tried editing od_watcher.py, but still no luck:
```
cat /home/v3ritas/.local/lib/python3.5/site-packages/onedrived/od_watcher.py | head -n 20
import logging
import os
import threading

import onedrivesdk.error
# Commenting this because the below doesn't work
# https://github.com/xybu/onedrived-dev/issues/77
# from bidict import loosebidict
class loosebidict(bidict.bidict):
    on_dup_val = bidict.OVERWRITE
from inotify_simple import flags as _inotify_flags, masks as _inotify_masks, INotify as _INotify

from .od_tasks import delete_item, move_item, merge_dir, update_mtime, upload_file
from .od_models.path_filter import PathFilter
from .od_api_helper import item_request_call
from .od_hashutils import hash_match
from .od_repo import ItemRecordType
from .od_stringutils import get_filename_with_incremented_count
```

I'm running on Linux Mint. Is there any additional info I should provide to determine why it worked for others, but no me?

**Comment by dloret** [comment]
Hi, are you sure you didn't forget to import indict?
```
import bidict
```

**Comment by veritas06** [comment]
I must be doing something wrong. Even after trying the import bidict, I still get the error. Thanks for the suggestion though.

**Comment by xybu** [comment]
Committed a fix in 4f24e4f3b2344ef5cdd9d167913bf32e6419a39b. Please try the latest version.

**Comment by derrix060** [comment]
@xybu close

**Comment by jab** [comment]
Hi from the author of bidict:)

Just wanted to suggest you pin to a known-compatible version in your requirements.txt in case there are any other breaking changes. So instead of:
https://github.com/xybu/onedrived-dev/blob/7189214d311a1f863c68c7fa808ce41d96dae958/requirements.txt#L12
change it to something like
```
bidict==0.18
```
I try to minimize breaking changes that are likely to bite users, but occasionally (after soliciting feedback and giving careful consideration), I do exercise the [major-version-zero](https://semver.org/#spec-item-4) prerogative, when the pros really outweigh the cons.

That said, sorry for the disruption this change caused. If you pin your dependencies as recommended above (which is generally best practice for applications anyway), it should protect you from breaking changes in the future.

Thanks for using bidict, and if you ever have any questions or feedback, please don't hesitate to drop a message in [the chat](https://gitter.im/jab/bidict). <333
