### ISSUE TITLE
"crash" when directory removed

### ISSUE THREAD

**Issue by rinyre** [xybu/onedrived-dev#84]
Discovered this trying to clean up a bunch of excess directories, but verified it with a single directory too. Any assistance would be awesome.

Problem: Deleting a directory causes onedrived to throw an exception.
Reproduce: Create a directory in sync'd OneDrive and remove it.

`[2017-12-15 05:29:14,609] INFO: MainThread: poll 2645541.020 ms took 26009.266 ms: 1 events
[2017-12-15 05:29:14,609] DEBUG: MainThread: Received inotify events. Acquiring lock.
[2017-12-15 05:29:14,810] DEBUG: MainThread: Read the following events: [(Event(wd=24, mask=1073742336, cookie=0, name='testdir'), [<flags.DELETE: 512>, <flags.ISDIR: 1073741824>]), (Event(wd=548, mask=32768, cookie=0, name=''), [<flags.IGNORED: 32768>])].
[2017-12-15 05:29:14,811] DEBUG: MainThread: Removing watcher for "<snip>/testdir"
[2017-12-15 05:29:14,811] ERROR: MainThread: Exception in callback LocalRepositoryWatcher.process_events()
handle: <Handle LocalRepositoryWatcher.process_events() created at /usr/lib/python3.4/asyncio/selector_events.py:177>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/onedrived", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/daemonocle/cli.py", line 57, in subcommand
    daemon.do_action(name)
  File "/usr/local/lib/python3.4/dist-packages/daemonocle/core.py", line 608, in do_action
    func()
  File "/usr/local/lib/python3.4/dist-packages/daemonocle/core.py", line 477, in start
    self._run()
  File "/usr/local/lib/python3.4/dist-packages/daemonocle/core.py", line 399, in _run
    self.worker()
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_main.py", line 204, in main
    context.watcher = LocalRepositoryWatcher(task_pool=task_pool, loop=context.loop)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_watcher.py", line 46, in __init__
    self.loop.add_reader(self.notifier.fd, self.process_events)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 177, in add_reader
    handle = events.Handle(callback, args, self)
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_watcher.py", line 441, in process_events
    self.handle_event(ev, flags, move_pairs)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_watcher.py", line 358, in handle_event
    self.rm_watch(repo, parent_dir + '/' + ev.name)
  File "/usr/local/lib/python3.4/dist-packages/onedrived/od_watcher.py", line 63, in rm_watch
    self.notifier.rm_watch(wd)
  File "/usr/local/lib/python3.4/dist-packages/inotify_simple/inotify_simple.py", line 110, in rm_watch
    _libc_call(_libc.inotify_rm_watch, self.fd, wd)
  File "/usr/local/lib/python3.4/dist-packages/inotify_simple/inotify_simple.py", line 68, in _libc_call
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 22] Invalid argument
[2017-12-15 05:29:14,813] WARNING: MainThread: Executing <Handle LocalRepositoryWatcher.process_events() created at /usr/lib/python3.4/asyncio/selector_events.py:177> took 0.203 seconds`

**Comment by ncolossi** [comment]
Same here. Did you find any solution?

Whenever I clean up some directory locally, I get a callback exception and the directory is not cleaned up in OneDrive.

[2018-06-07 08:27:49,246] ERROR: MainThread: Exception in callback LocalRepositoryWatcher.process_events()
handle: <Handle LocalRepositoryWatcher.process_events()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_watcher.py", line 441, in process_events
    self.handle_event(ev, flags, move_pairs)
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_watcher.py", line 339, in handle_event
    repo, parent_dir = self.watch_descriptors[ev.wd]
  File "/home/nathan/.local/lib/python3.5/site-packages/bidict/_common.py", line 96, in proxy
    return meth(*args)

Using ubuntu 16.04.4, python 3.5.2.

Any help appreciated!
