### ISSUE TITLE
onedrived-pref wrong

### ISSUE THREAD

**Issue by updater1234** [xybu/onedrived-dev#93]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/backends/kwallet.py", line 37, in priority
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
AttributeError: module 'dbus' has no attribute 'SessionBus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/onedrived-2.0.0-py3.6.egg/onedrived/od_pref.py", line 9, in <module>
    import keyring
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/core.py", line 153, in <module>
    init_backend()
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/core.py", line 66, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/backend.py", line 196, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/backend.py", line 188, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/backends/kwallet.py", line 135, in priority
    return super(DBusKeyringKWallet4, cls).priority - 1
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3.6/site-packages/keyring-11.0.0-py3.6.egg/keyring/backends/kwallet.py", line 38, in priority
    except dbus.DBusException as exc:
AttributeError: module 'dbus' has no attribute 'DBusException'

**Comment by derrix060** [comment]
What version of keyring is you using? Check it running `pip3 freeze | grep keyring`. I'm running with this one:

```
keyring==11.0.0
keyrings.alt==3.0
```
