### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by pniedzwiedzinski** [xybu/onedrived-dev#95]
I was renaming (moving) a directory when this error occured. Directory was empty.

```ERROR: MainThread: Exception in callback LocalRepositoryWatcher.process_events()
handle: <Handle LocalRepositoryWatcher.process_events()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/------/.local/lib/python3.5/site-packages/onedrived/od_watcher.py", line 441, in process_events
    self.handle_event(ev, flags, move_pairs)
  File "/home/------/.local/lib/python3.5/site-packages/onedrived/od_watcher.py", line 339, in handle_event
    repo, parent_dir = self.watch_descriptors[ev.wd]
  File "/home/------/.local/lib/python3.5/site-packages/bidict/_base.py", line 411, in __getitem__
    return self._fwdm[key]
KeyError: 15

**Comment by derrix060** [comment]
Do you have the logs from this run? It looks like the `LocalRepositoryWatcher` tried to access some event that doesn't exist anymore.

**Comment by butterfly-pn** [comment]
No, I have not, but if this error occurs again, I will send it to you.
